server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/el_proyecte_grande
    username: postgres
    password: Steaua93

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  main:
    web-application-type: servlet

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem